### ISSUE TITLE
Is it just me or is loading pages in the thesaurus terribly slow?

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/geothesaurus#4]
Pages take 3 - 4 seconds to load.
This was not a problem before.... and the only thing that changed (I think) is the domain.
@mmmenno  Or has something else changed?

Could this be some weird DNS issue?

**Comment by mmmenno** [comment]
@w0ps @w0ps any ideas? Since new DNS settings thesaurus pages take up to 3 seconds(!) to load. Same thing happens with standaardiseren.erfgeo.nl

**Comment by Ivokato** [comment]
I'm sorry, I don't know yet. Have you checked the network tab of your
inspector to see what is taking so long?

**Comment by phpetra** [comment]
Maybe this should be @wires ?

@w0ps If you'd had a look, you'll see that it's not loading any other resource, internal or external but that the response from the server takes that long. And this has changed dramatically since the DNS alterations.

**Comment by Ivokato** [comment]
now I wonder why github response takes longer after a dns change.. seems a
bit beyond our control..

On Wed, Jun 17, 2015 at 3:02 PM, Petra Dreiskämper <notifications@github.com

**Comment by phpetra** [comment]
@w0ps It's not github... it is our own old (Rein) server.... the subdomains:
standaardiseren.erfgeo.nl
importeren.erfgeo.nl
thesaurus.erfgeo.nl

**Comment by Ivokato** [comment]
als het met die machine te maken heeft kan @wires er misschien meer mee ja, die heeft daar in ieder geval toegang op

**Comment by phpetra** [comment]
@mmmenno Kun jij die HOSTname daarin anders weer even terugzetten? (al is het maar voor morgen)

**Comment by bertspaan** [comment]
Als 't alleen 't afgelopen uur was kan 't komen omdat ik als een bezetene PIT'jes en relaties aan 't importeren was :floppy_disk: :floppy_disk: :floppy_disk: :floppy_disk: :floppy_disk: :floppy_disk:

**Comment by phpetra** [comment]
@bertspaan Zie de datum van de eerste melding..... het is sinds de DNS omzetting zo. Het heeft volgens mij ook niks met eventuele aangepaste code op de server te maken maar ik denk aan een network-issue door die DNS-wijziging.
Wat we eventueel kunnen uitsluiten door die hostname weer aan te passen, daarna weten we meer.

**Comment by wires** [comment]
OK ik ga even kijkje nemen.

**Comment by wires** [comment]
Cannot reproduce, all requests, include DNS respond within about 100ms. You can have a look yourself using chrome developer tools, see
- https://developers.google.com/web/fundamentals/performance/critical-rendering-path/analyzing-crp?hl=en or
- https://developer.chrome.com/devtools/docs/timeline or
- https://developer.chrome.com/devtools/docs/network#resource-network-timing

Also I doubt this is DNS related, because all that happened is that we went from a catch all zone `*` to specific zones in the DNS.

I do see CDN timing out on leaflet and it is causing a (400ms) delay, but this could be related to my browser.

Also, quite a bit of time is spent parsing the HTML and executing scripts (600ms)

**Comment by wires** [comment]
Ah, after more browsing, I see something. It is the `/pit` resource that takes very long!

![screen shot 2015-06-18 at 10 03 09](https://cloud.githubusercontent.com/assets/315734/8226718/8eb978b0-15a1-11e5-8275-41388cff1514.png)

**Comment by wires** [comment]
OK seems HTTPS API is slow from the new (api.erfgeo.nl)and old vps (api.histograph.io)?!?

From old vps to new:

```
jelle@localhost:~$ time curl https://api.erfgeo.nl
{...}
real    0m3.030s
user    0m0.008s
sys 0m0.004s
```

from new vps to itself

```
time curl https://api.erfgeo.nl
{...}
real    0m3.025s
user    0m0.005s
sys 0m0.005s
```

op mijn machine

```
time curl https://api.erfgeo.nl
{....}        0.14 real         0.06 user         0.00 sys
```

WHAT TEH

**Comment by wires** [comment]
IPv6 record in DNS doesn't resolve

```
root@vps862:/home/jelle# curl -vvv https://api.erfgeo.nl
* About to connect() to api.erfgeo.nl port 443 (#0)
*   Trying 2a02:2308::216:3eff:feb3:a84b...
* No route to host
*   Trying 178.21.113.147...
```

**Comment by wires** [comment]
Tuned `nginx` to listen to IPv6 address,

```
netstat -nlp | grep nginx
tcp6       0      0 :::80                   :::*                    LISTEN      21554/nginx
tcp6       0      0 :::443                  :::*                    LISTEN      21554/nginx
```

but no sigar, yet.

```
curl -6 -vvv api.erfgeo.nl
* About to connect() to api.erfgeo.nl port 80 (#0)
*   Trying 2a02:2308::216:3eff:feb3:a84b...
* No route to host
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
```

**Comment by wires** [comment]
I don't know what is up, need to contact Direct VPS, cannot seem to ping6 the new VPS.

```
root@localhost:/home/jelle# ping vps862.directvps.nl
PING vps862.directvps.nl (178.21.113.147) 56(84) bytes of data.
64 bytes from vps862.directvps.nl (178.21.113.147): icmp_req=1 ttl=60 time=1.21 ms
64 bytes from vps862.directvps.nl (178.21.113.147): icmp_req=2 ttl=60 time=1.26 ms
64 bytes from vps862.directvps.nl (178.21.113.147): icmp_req=3 ttl=60 time=1.17 ms
^C
--- vps862.directvps.nl ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 1.176/1.218/1.261/0.053 ms
root@localhost:/home/jelle# ping6 vps862.directvps.nl
PING vps862.directvps.nl(vps862.directvps.nl) 56 data bytes
From a3942.compukos.atom86.net icmp_seq=1 Destination unreachable: Address unreachable
From a3942.compukos.atom86.net icmp_seq=2 Destination unreachable: Address unreachable
From a3942.compukos.atom86.net icmp_seq=3 Destination unreachable: Address unreachable
```

VPS config:

```
eth0      Link encap:Ethernet  HWaddr 00:16:3e:3b:3b:da
          inet addr:178.21.113.147  Bcast:178.21.113.255  Mask:255.255.255.0
          inet6 addr: 2a02:2308::216:3eff:fe3b:3bda/64 Scope:Global
          inet6 addr: fe80::216:3eff:fe3b:3bda/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:80178452 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6121527 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:7100484626 (6.6 GiB)  TX bytes:2559469290 (2.3 GiB)
```

DNS records

```
dig AAAA vps862.directvps.nl

; <<>> DiG 9.8.3-P1 <<>> AAAA vps862.directvps.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41020
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;vps862.directvps.nl.       IN  AAAA

;; ANSWER SECTION:
vps862.directvps.nl.    19277   IN  AAAA    2a02:2308::216:3eff:feb3:a84b

;; Query time: 215 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jun 18 11:12:23 2015
;; MSG SIZE  rcvd: 65
```

I'm not going to change any configuration now, given the workshop today! Requests from participants are fast, because they are in the Waag which doesn't support IPv6.
