### ISSUE TITLE
Search on homepage leads to old api.histograph.io

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/geothesaurus#5]
On the erfgeo.nl homepage: search in the thesaurus and click the "zoek" button -> you end up in the old API.

Apparently it's possible (in some browsers) to hit enter and you end up in the correct api viewer, but in my browser (firefox) hitting enter doesn't do anything

**Comment by Ivokato** [comment]
Je hebt dit issue onder de verkeerde repository aangemaakt. Is opgelost, zowel enter toets als goede api url
