### ISSUE TITLE
PHP Error in results list

### ISSUE THREAD

**Issue by KitsR** [erfgoed-en-locatie/geothesaurus#6]
When searching for "wijk" (query = http://thesaurus.erfgeo.nl/?q=wijk) a PHP Error is visible as one of the results in the list: 

A PHP Error was encountered
Severity: Notice
Message: Undefined index: id
Filename: helpers/erfgeo_helper.php
Line Number: 22
">Wijk, hg:Place

This search result links to detail page http://thesaurus.erfgeo.nl/hgconcept/?id=%3Cdiv%20style=.

**Comment by jobspierings** [comment]
fixed.
